[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts"
]

[fmt]
quote_style = 'single'
int_types = 'short'

[rpc_endpoints]
linea = 'https://linea-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
